project:
  type: website

website:
  title: "Hiten Ladkani - Data Analyst Portfolio"
  description: "Showcasing analytics projects that solve real-world Marketing & Healthcare problems."
  site-url: "https://hiten317.github.io/"
  repo-url: https://github.com/hiten317?tab=repositories
  navbar:
    background: primary
    left:
      - about.qmd
      - projects.qmd
      - resume.qmd
      - contact.qmd

format:
  html:
    theme: flatly
    css: custom.css



